#!/bin/sh
set -e

if [ "$1" = "configure" ] ; then
	TEMP=$(mktemp -d /tmp/arduinoprebuilt.XXXXX)
	cd /usr/share/arduino/hardware/UDOO/solox/variants/udooneo/
	for file in *.c; do
		echo "Building $file"
		/usr/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -fmessage-length=0 -D_AEABI_LC_CTYPE=C -D__STRICT_ANSI__=1 -MMD -DF_CPU=227368421L -DARDUINO=10605 -DARDUINO_UDOO_NEO -DARDUINO_ARCH_SOLOX -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release/bsp -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release/bsp/Sources -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release/psp -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release/mcc -DARDUINO=123456 -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -I/usr/share/arduino/hardware/UDOO/solox/cores/arduino -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo /usr/share/arduino/hardware/UDOO/solox/variants/udooneo/$file -o $TEMP/$file.o
	done

	for file in *.cpp; do
		echo "Building $file"
		/usr/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fmessage-length=0 -D_AEABI_LC_CTYPE=C -D__STRICT_ANSI__=1 -fabi-version=0 -MMD -DF_CPU=227368421L -DARDUINO=10605 -DARDUINO_UDOO_NEO -DARDUINO_ARCH_SOLOX -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release/bsp -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release/bsp/Sources -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release/psp -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo/mqx/release/mcc -DARDUINO=123456 -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -I/usr/share/arduino/hardware/UDOO/solox/cores/arduino -I/usr/share/arduino/hardware/UDOO/solox/variants/udooneo /usr/share/arduino/hardware/UDOO/solox/variants/udooneo/$file -o $TEMP/$file.o
	done
	
	echo "Linking files..."
	/usr/bin/arm-none-eabi-ar rcs udooneo.a $TEMP/*.o
	rm -rf $TEMP
	sed -i 's;/\* udooneo.a \*/;udooneo.a;' linker_scripts/gcc/libs.ld
	echo "Archiving sources..."
	tar cfz udooneo.tgz *.c *.cpp
	rm *.c *.cpp
fi

exit 0

